Bad Commit
moevm/nosql2h23-genealogy pull request #34
Opened 2023-11-25 16:10 UTC by PichuginMaksim0303

2023-11-25 16:15 UTC, AntonSeredenkov commented on project/Frontend/src/components/AddNodePage.vue
> +    const login = ref("IvanIvan@gmail.com")
А нам точно нужен логин и пароль для узлов родственников?

2023-11-25 16:17 UTC, AntonSeredenkov commented on project/Frontend/src/components/TreePage.vue
> +        @click="$router.push('/addNode')"
В самом роутере прописано обращение к этому пути?

2023-11-25 16:37 UTC, severus2293 requested changes

2023-11-25 16:37 UTC, severus2293 commented on project/Backend/package-lock.json
> +        "neo4j-driver": "^5.12.0"
чем обоснованы такие изменения?

2023-11-25 16:37 UTC, severus2293 commented on project/Frontend/src/components/AddNodePage.vue
> +    const login = ref("IvanIvan@gmail.com")
Я конечно говорил, что страница профиля похоже на страницу добавления, но не под копирку же, а лишь визуально.

2023-11-25 16:37 UTC, severus2293 commented on project/Frontend/src/components/AddNodePage.vue
> +    const login = ref("IvanIvan@gmail.com")
ну и когда я говорил про добавление узла, я имел ввиду добавление узла - страница добавления + логика добавления

2023-11-26 08:55 UTC, severus2293 commented
Я подправил запрос и отправку данных. Теперь узел должен добавляться. Теперь нужно прикрутить чтобы узел привязывался к дереву
![Снимок экрана (336)](https://github.com/moevm/nosql2h23-genealogy/assets/71723580/73d276e8-826e-478c-87ff-d7ba495a25e8)
Здесь нужно для первого селекта доставать все узлы из бд для конкретного дерева, второй селект в принципе просто типы отношений, это пока можно захардкодить.

2023-11-27 20:11 UTC, severus2293 approved these changes

2023-11-27 20:38 UTC, merged